name: AdvancedHoppers
version: "${version}"
main: com.courtega.advancedhoppers.AdvancedHoppers
api-version: "1.20"
authors: [ courtega, Fruitloopins ]
description: Create filtered hoppers using expressions.
website: https://courtega.com
folia-supported: true

commands:
  advancedhoppers:
    description: Create filtered hoppers using expressions.
    usage: /advancedhoppers

libraries:
  - com.moandjiezana.toml:toml4j:0.7.1