name: FilteredHoppers
version: "${project.version}"
main: com.courtega.advancedhoppers.FilteredHoppersPlugin
api-version: "1.20"
authors: [ courtega, Fruitloopins ]
description: Create filtered hoppers using expressions.
website: https://courtega.com
folia-supported: true

commands:
  advancedhoppers:
    description: Your description
    usage: /advancedhoppers [help]

libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.5.7